# API for testing environment

# List all products
GET https://devstore-api-iota.vercel.app/api/products

###
# List only featured products
GET https://devstore-api-iota.vercel.app/api/products/featured

###
# Get a single product
GET https://devstore-api-iota.vercel.app/api/products/moletom-never-stop-learning

###
# Search products
GET https://devstore-api-iota.vercel.app/api/products/search?q=camiseta
